renew project
Asteises/java-shareit-yandex-new pull request #1
Opened 2022-09-10 15:27 UTC by Asteises

2022-09-11 12:08 UTC, alexache requested changes

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +//    private long request;
По ТЗ это должно быть

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +//                item.getRequest() != null ? item.getRequest().getId() : null
По ТЗ должно быть

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +            User user = userStorage.findById(userId);
2 раза выполняется userStorage.findById Лучше сразу сохранять результат в переменную

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +                throw new ResponseStatusException(HttpStatus.BAD_REQUEST);
Это и в сервисе не очень уместно. логичнее тут бросать обычный эксепшен, который через RestControllderAdvice будет смаплен на нужный резалт код

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND);
Такого рода эксепшен с указанием резалт кода не очень хорошо. потому что приводит к смешиванию слоев и логики, лучше все логику по связыванию исключений и резаль кодов хранить в RestControllerAdvice

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +                .map(item -> new ItemDto(
Почему нигде не используется ItemMapper?

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repositores/ItemDao.java
> +                    .filter(item -> (item.getName().toLowerCase().contains(text.toLowerCase()))
text.toLowerCase сохранить в переменную в начале метода, чтобы не делать эту операцию повторно

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repositores/ItemDao.java
> +            findItems.addAll(items.values().stream()
Зачем через addAll, а не просто вернуть как есть полученный лист после стрима?

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repositores/ItemDao.java
> +    public ItemDto save(Item item) {
Пусть ItemDao ничего не знает про ItemDto. Пускай сервис занимается вызовом маппера

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +                User user = userStorage.findById(userId);
Повторный вызов userStorage.findById

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +                throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR);
Комментарий, как и для ItemServiceImpl - лучше иметь обычный эксепшен, и маппит на резалт код в RestControllerAdvice

2022-09-11 12:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +            userStorage.delete(userId);
Возможно, стоит сделать так, чтобы delete возвращал удаленный объект, чтобы не вызывать поиск по айди повторно

2022-09-12 10:40 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +//    private long request;
Исправил

2022-09-12 10:40 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +//                item.getRequest() != null ? item.getRequest().getId() : null
Исправил

2022-09-12 10:46 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +            User user = userStorage.findById(userId);
Исправил

2022-09-12 11:16 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +                .map(item -> new ItemDto(
Исправил

2022-09-12 11:20 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/repositores/ItemDao.java
> +                    .filter(item -> (item.getName().toLowerCase().contains(text.toLowerCase()))
Исправил

2022-09-12 11:25 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/repositores/ItemDao.java
> +            findItems.addAll(items.values().stream()
Исправил

2022-09-12 12:35 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +                throw new ResponseStatusException(HttpStatus.BAD_REQUEST);
Про ексепшены ничего не понял... 
Как лучше сделать?

2022-09-12 12:35 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND);
Про ексепшены ничего не понял... 
Как лучше сделать?

2022-09-12 12:52 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/repositores/ItemDao.java
> +    public ItemDto save(Item item) {
Исправил

2022-09-12 13:47 UTC, Asteises commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +                User user = userStorage.findById(userId);
Исправил

2022-09-12 13:47 UTC, Asteises commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +                throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR);
Про ексепшены ничего не понял...
Как лучше сделать?

2022-09-12 13:49 UTC, Asteises commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +            userStorage.delete(userId);
сделал через try catch

2022-09-13 07:15 UTC, alexache requested changes

2022-09-13 07:15 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        item.setRequest(new ItemRequest());
А где выставление юзера? Можно добавить еще два аргумента в этот метод, чтобы передавать юзера и реквест из сервиса. Реквест пока всегда будет null

2022-09-13 07:15 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> -                        item.getAvailable())).collect(Collectors.toList());
Тоже должно происходить через маппер

2022-09-13 07:15 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +
По ТЗ больше полей

2022-09-13 07:15 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +        } catch (UserNotFound e) {
Зачем тогда делать catch, если модно оставить этот эксепшен

2022-09-13 07:52 UTC, Asteises commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +
Исправил

2022-09-13 07:53 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/services/ItemServiceImpl.java
> -                        item.getAvailable())).collect(Collectors.toList());
Исправил

2022-09-13 08:24 UTC, Asteises commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +            userStorage.delete(userId);
исправил, но не возвращая удаленный объект, так как не пойму как сделать так, чтобы запрос был только один к БД. У меня получается всегда два.

2022-09-13 08:25 UTC, Asteises commented on src/main/java/ru/practicum/shareit/user/services/UserServiceImpl.java
> +        } catch (UserNotFound e) {
исправил, но не возвращая удаленный объект, так как не пойму как сделать так, чтобы запрос был только один к БД. У меня получается всегда два.

2022-09-13 08:26 UTC, Asteises commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        item.setRequest(new ItemRequest());
Исправил

2022-09-14 09:22 UTC, alexache approved these changes

2022-09-14 11:50 UTC, merged